name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.12", "3.13", "3.14"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v6

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          environment-file: environment.yml
          activate-environment: pplpy-build

      - name: Install test dependencies
        run: conda env update --file environment.test.yml

      - name: Lint
        run: |
          cython-lint --ignore=E265,E266,E501,E741 --exclude='ppl_decl.pxd' ppl/

      - name: Build (meson)
        run: |
          meson setup builddir
          meson compile -C builddir

      - name: Test (meson test)
        run: |
          meson test -C builddir -v

      - name: Show logs
        run: cat builddir/meson-logs/testlog.txt || true
        if: ${{ always() }}
